export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const IS_MY_COURSES = 'IS_MY_COURSES';
export const START_UPDATING_COURSE = 'START_UPDATING_COURSE';
export const END_UPDATING_COURSE = 'END_UPDATING_COURSE';
export const START_DELETING_COURSE = 'START_DELETING_COURSE';
export const END_DELETING_COURSE = 'END_DELETING_COURSE';
export const START_CREATING_COURSE = 'START_CREATING_COURSE';
export const END_CREATING_COURSE = 'END_CREATING_COURSE';
export const START_SEARCHING_COURSE = 'START_SEARCHING_COURSE';
export const END_SEARCHING_COURSE = 'END_SEARCHING_COURSE';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const SET_LOADING_USER_ID_COACH = 'SET_LOADING_USER_ID_COACH';
export const UNSET_LOADING_USER_ID_COACH = 'UNSET_LOADING_USER_ID_COACH';
export const SET_LOADING_COURSE_ID_COACH = 'SET_LOADING_COURSE_ID_COACH';
export const UNSET_LOADING_COURSE_ID_COACH = 'UNSET_LOADING_COURSE_ID_COACH';
export const SET_LOADING_COURSE_ID = 'SET_LOADING_COURSE_ID';
export const UNSET_LOADING_COURSE_ID = 'UNSET_LOADING_COURSE_ID';
export const FETCH_ALL_CU = 'FETCH_ALL_CU';
export const CREATE_CU = 'CREATE_CU';
export const START_CREATING_COURSE_USER = 'START_CREATING_COURSE_USER';
export const END_CREATING_COURSE_USER = 'END_CREATING_COURSE_USER';
export const UPDATE_CU = 'UPDATE_CU';
export const DELETE_CU = 'DELETE_CU';
export const START_DELETING_COURSE_USER = 'START_DELETING_COURSE_USER';
export const END_DELETING_COURSE_USER = 'END_DELETING_COURSE_USER';


export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const START_LOADING_AUTH = 'START_LOADING_AUTH';
export const END_LOADING_AUTH = 'END_LOADING_AUTH';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const START_LOADING_FETCH_ALL_USERS = 'START_LOADING_FETCH_ALL_USERS';
export const END_LOADING_FETCH_ALL_USERS = 'END_LOADING_FETCH_ALL_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const START_LOADING_UPDATE_USER = 'START_LOADING_UPDATE_USER';
export const END_LOADING_UPDATE_USER = 'END_LOADING_UPDATE_USER';
export const WRONG = 'WRONG';
export const FAILPWRESET = 'FAILPWRESET';
export const RECOVER = 'RECOVER';
export const RESETPW = 'RESETPW';

